version: "3.3"
services:
  web:
    build: web/
    ports:
      - "80:80"
    volumes:
      # Nginx settings refer to http://nginx.org/en/docs/beginners_guide.html
      - /usr/local/dublinbus/config/web/nginx.conf:/etc/nginx/nginx.conf:ro
#      - /usr/local/dublinbus/config/web/web/index.html:/flutter/web/web/index.html
    environment:
      - NGINX_HOST=${NGINX_HOST}
      - NGINX_PORT=80
    depends_on:
      - api
  api:
    build: api/
    volumes:
      - /usr/local/dublinbus/config/api:/app/config:ro
    ports:
      - "10000:8080"
        #    depends_on:
      #- mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_ROOT_HOST=${MONGO_INITDB_ROOT_HOST}
      - MONGO_INITDB_ROOT_PORT=${MONGO_INITDB_ROOT_PORT}
  scraper:
    build: scraper/
    volumes:
      - /usr/local/dublinbus/config/scraper:/app/scripts/config:ro
      - /usr/local/dublinbus/data:/app/scripts/data:ro
  mysql:
    image: "mysql:8.0.29"
    ports:
      - "442:3306"
    volumes:
      - /usr/local/dublinbus/mysql/:/var/lib/mysql
    environment:
      # Initialize the database with proper permissions. Refer to https://hub.docker.com/_/mysql
      # - The MYSQL_ROOT_PASSWORD is mandatory
      # - The MYSQL_USER and MYSQL_PASSWORD are created for project use with access to MYSQL_DATABASE
      - MYSQL_ROOT_PASSWORD={MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=diytest
      - MYSQL_PASSWORD=${MYSQL_USER_PASSWORD}
      - MYSQL_DATABASE=diyTestDb
  mongodb:
    image: "mongo"
    volumes:
      - /usr/local/dublinbus/database:/data/db
    ports:
      - 10100:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
