version: "3.3"
services:
  web:
    build: web/
    ports:
      - 80:80
    depends_on:
      - api
  api:
    build: api/
    volumes:
      - /usr/local/dublinbus/config/api:/app/config:ro
    ports:
      - 10000:8080
        #    depends_on:
      #- mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_ROOT_HOST=${MONGO_INITDB_ROOT_HOST}
      - MONGO_INITDB_ROOT_PORT=${MONGO_INITDB_ROOT_PORT}
  scraper:
    build: scraper/
    #environment:
    #  - MONGODB_CONNSTRING=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb
    volumes:
      - /usr/local/dublinbus/config/scraper:/app/scripts/config:ro
      - /usr/local/dublinbus/data:/app/scripts/data:ro
    depends_on:
      - mongodb
  mongodb:
    image: "mongo"
    volumes:
      - /usr/local/dublinbus/database:/data/db
    ports:
      - 442:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
