version: "3.3"
services:
  web:
    build: web/
    ports:
      - 80:80
    #depends_on:
    #  - go
  scraper:
    build: scraper/
    #environment:
    #  - MONGODB_CONNSTRING=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb
    volumes:
      - /usr/local/dublinbus/config/scraper:/app/scripts/config:ro
    depends_on:
      - mongodb
  mongodb:
    image: "mongo"
    volumes:
      - /usr/local/dublinbus/database:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
