version: "3.3"
services:
  web:
    build: web/
    ports:
      - 80:80
    depends_on:
      - api
  api:
    build: api/
    volumes:
      - /usr/local/dublinbus/config/api:/app/config:ro
    ports:
      - 10000
  scraper:
    build: scraper/
    volumes:
      - /usr/local/dublinbus/config/scraper:/app/scripts/config:ro
      - /usr/local/dublinbus/data:/app/scripts/data:ro
  mysql:
    image: "mysql:8.0.29"
    ports:
      - 442:3306
    volumes:
      - /usr/local/dublinbus/mysql/:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/usr/local/dublinbus/secrets/mysql-root
