version: "3.9"
services:
  web:
    build: .
    ports:
      - "80:80"
  scraper:
    build: .
    depends_on:
      - mongo
  mongo:
    image: "mongo"
    volumes:
        - /usr/local/dublinbus/database:/data/db
